sudo: required

language: bash

branches:
  only:
  - master
  - production

services:
  - docker

before_install:
   - docker build -t DOCKER-ID/mads-todolist-2017:0.2 .

script:
   - docker run --rm DOCKER-ID/mads-todolist-2017:0.2 /bin/bash -c "sbt test"
